//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class FrmAbmDocente {
    
    protected System.Web.UI.WebControls.Content BodyContent;
    
    protected System.Web.UI.WebControls.Repeater repDocentes;
    
    protected System.Web.UI.WebControls.Label lblNombre;
    
    protected System.Web.UI.WebControls.Label lblApellido;
    
    protected System.Web.UI.WebControls.Label lblDocumento;
    
    protected System.Web.UI.WebControls.Label lblCelular;
    
    protected System.Web.UI.WebControls.Label lblCorreo;
    
    protected System.Web.UI.WebControls.LinkButton btnEditar;
    
    protected System.Web.UI.WebControls.LinkButton btnConfirma;
    
    protected System.Web.UI.WebControls.LinkButton btnNuevo;
}
