//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class FrmAbmUsuario {
    
    protected System.Web.UI.WebControls.Content Content1;
    
    protected System.Web.UI.WebControls.Content contenido;
    
    protected System.Web.UI.WebControls.TextBox txtNombre;
    
    protected System.Web.UI.WebControls.TextBox txtClave;
    
    protected System.Web.UI.WebControls.DropDownList listDocentes;
    
    protected System.Web.UI.WebControls.Button btnPrincipal;
    
    protected System.Web.UI.WebControls.Button btnGuardar;
}
