//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class FrmEditarDocente {
	
	protected System.Web.UI.WebControls.Content BodyContent;
	
	protected System.Web.UI.WebControls.TextBox txtNombre;
	
	protected System.Web.UI.WebControls.TextBox txtApellido;
	
	protected System.Web.UI.WebControls.TextBox txtNroDocumento;
	
	protected System.Web.UI.WebControls.TextBox txtCelular;
	
	protected System.Web.UI.WebControls.TextBox txtCorreo;
	
	protected System.Web.UI.WebControls.LinkButton btnVolver;
	
	protected System.Web.UI.WebControls.LinkButton btnEditar;
	
	protected System.Web.UI.WebControls.LinkButton btnConfirma;
}
